apiVersion: v1
kind: Template

labels:
  application: scavenger

metadata:
  name: scavenger

parameters:
  - name: SECRET_NAME
    value: scavenger
    required: true
  - name: S3_ACCESS_KEY_ID
    value: ""
  - name: S3_SECRET_ACCESS_KEY
    value: ""
  - name: S3_ENDPOINT
    value: ""
  - name: S3_REGION
    value: ""
  - name: S3_BUCKET
    value: ""
  - name: S3_PREFIX
    value: ""
  - name: MODEL_LOCATION
    value: "saved_model"
  - name: MODEL_CONFIG_LOCATION
    value: "model_config.json"

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
    data:
    stringData:
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_REGION: "${S3_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_PREFIX: "${S3_PREFIX}"
      MODEL_LOCATION: "${MODEL_LOCATION}"
      MODEL_CONFIG_LOCATION: "${MODEL_CONFIG_LOCATION}"
