apiVersion: v1
kind: Template

labels:
  application: scavenger-server

metadata:
  name: scavenger-server

parameters:
  - name: APPLICATION_NAME
    value: scavenger-server
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: PORT
    value: "8080"
    required: true
  - name: IP
    value: "0.0.0.0"
    required: true
  - name: IMAGE_REPOSITORY
    value: quay.io/cfchase/scavenger-server:latest
    required: true


objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${APPLICATION_NAME}
    data:
    stringData:
      EXAMPLE_KEY: "example_value"

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: IP
                  value: "${IP}"
                - name: PORT
                  value: "${PORT}"
              envFrom:
                - secretRef:
                    name: ${APPLICATION_NAME}
              image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                httpGet:
                  path: /api/status
                  port: 8080
                  scheme: HTTP
              livenessProbe:
                httpGet:
                  path: /api/status
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APPLICATION_NAME}
